@var = http://localhost:3000/user

GET {{var}}

###
POST {{var}}
Content-Type: application/json

{
    "nome": "teste",
    "preco": 333.33
}

###
GET {{var}}/<:id>
###

PUT {{var}}/<:id>
Content-Type: application/json

{
    "nome": "teste2",
    "preco": 99.99
}
###
DELETE {{var}}/<:id>